"use client";

import React, { useState } from 'react';
import { useIdentityTrust } from '../context/IdentityTrustContext';
import { SOCAlert } from '../utils/mockDataGenerator';
import { ShieldAlert, Check, X, Search, Filter, Shield, AlertTriangle, AlertOctagon, HelpCircle } from 'lucide-react';

export const AlertsCenter: React.FC = () => {
  const { alerts, resolveAlert, setView, setSelectedAlert } = useIdentityTrust();
  
  const [activeTab, setActiveTab] = useState<'all' | 'open' | 'investigating' | 'resolved'>('all');
  const [severityFilter, setSeverityFilter] = useState<'all' | 'critical' | 'high' | 'medium' | 'low'>('all');
  const [localSearch, setLocalSearch] = useState<string>('');

  const getSeverityBadge = (severity: string) => {
    switch(severity) {
      case 'critical': return 'text-red-500 bg-red-500/10 border-red-500/20';
      case 'high': return 'text-orange-400 bg-orange-500/10 border-orange-500/20';
      case 'medium': return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
      case 'low': return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
      default: return 'text-slate-400 border-slate-800 bg-slate-900';
    }
  };

  const handleInvestigate = (alert: SOCAlert) => {
    setSelectedAlert(alert);
    setView('investigation');
  };

  const handleResolve = (id: string, action: 'resolved' | 'dismissed') => {
    resolveAlert(id, action);
  };

  // Filter alerts
  const filteredAlerts = alerts.filter(alert => {
    const matchesTab = activeTab === 'all' || alert.status === activeTab;
    const matchesSeverity = severityFilter === 'all' || alert.severity === severityFilter;
    const matchesSearch = localSearch === '' || 
      alert.customerName.toLowerCase().includes(localSearch.toLowerCase()) ||
      alert.description.toLowerCase().includes(localSearch.toLowerCase()) ||
      alert.type.toLowerCase().includes(localSearch.toLowerCase()) ||
      alert.ipAddress.includes(localSearch) ||
      alert.id.includes(localSearch);

    return matchesTab && matchesSeverity && matchesSearch;
  });

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold tracking-wide text-slate-100 font-sans">Real-Time Alerts Hub</h1>
          <p className="text-xs text-slate-400 font-sans mt-0.5">Continuous incident notifications feed generated by the Vector database and AI trust scoring modules.</p>
        </div>
      </div>

      {/* Control Filters bar */}
      <div className="glass-panel p-4 rounded-xl border border-slate-850 flex flex-col md:flex-row justify-between gap-4 items-center">
        
        {/* Status Tabs */}
        <div className="flex gap-1 bg-slate-950 p-1 rounded-lg border border-slate-900 shrink-0 w-full md:w-auto">
          {['all', 'open', 'investigating', 'resolved'].map(status => (
            <button 
              key={status}
              onClick={() => setActiveTab(status as any)}
              className={`flex-1 md:flex-initial px-3 py-1 text-[11px] font-mono rounded cursor-pointer transition-all uppercase ${
                activeTab === status ? 'bg-slate-800 text-cyan-400 font-bold' : 'text-slate-500 hover:text-slate-350'
              }`}
            >
              {status} ({
                status === 'all' 
                  ? alerts.length 
                  : alerts.filter(a => a.status === status).length
              })
            </button>
          ))}
        </div>

        {/* Severity Select */}
        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="relative flex-1 md:w-48">
            <span className="absolute inset-y-0 left-2.5 flex items-center text-slate-500">
              <Search size={12} />
            </span>
            <input 
              type="text"
              placeholder="Search alerts..."
              value={localSearch}
              onChange={(e) => setLocalSearch(e.target.value)}
              className="w-full bg-slate-950/60 border border-slate-800 rounded-lg pl-8 pr-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-cyan-500/60"
            />
          </div>

          <div className="relative shrink-0">
            <select 
              value={severityFilter}
              onChange={(e: any) => setSeverityFilter(e.target.value)}
              className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-400 focus:outline-none focus:border-cyan-500/60"
            >
              <option value="all">All Severities</option>
              <option value="critical">Critical Only</option>
              <option value="high">High & Above</option>
              <option value="medium">Medium Only</option>
              <option value="low">Low Only</option>
            </select>
          </div>
        </div>

      </div>

      {/* Alerts Grid list */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => {
          const isOpen = alert.status === 'open' || alert.status === 'investigating';
          
          return (
            <div 
              key={alert.id}
              className={`glass-panel p-5 rounded-2xl border border-slate-850 flex flex-col md:flex-row justify-between gap-5 relative overflow-hidden transition-all duration-200 hover:border-slate-800 ${
                alert.status === 'resolved' ? 'opacity-60' : ''
              }`}
            >
              {/* Alert Content */}
              <div className="space-y-2 flex-1">
                <div className="flex flex-wrap items-center gap-2.5">
                  <span className={`text-[9px] font-mono font-bold px-1.5 py-0.5 rounded border uppercase ${getSeverityBadge(alert.severity)}`}>
                    {alert.severity}
                  </span>
                  <span className="text-xs font-bold text-slate-200 font-sans">{alert.type}</span>
                  <span className="text-[10px] font-mono text-slate-500">{alert.id} &bull; {new Date(alert.timestamp).toLocaleString()}</span>
                </div>

                <p className="text-[11px] text-slate-400 leading-relaxed font-sans max-w-2xl">
                  {alert.description}
                </p>

                {/* Telemetry info */}
                <div className="flex flex-wrap items-center gap-4 text-[10px] font-mono text-slate-500 pt-1">
                  <div>User ID: <strong className="text-slate-400">{alert.customerId}</strong> ({alert.customerName})</div>
                  <div>IP: <strong className="text-slate-400">{alert.ipAddress}</strong> ({alert.location})</div>
                </div>

                {/* Recommended Actions */}
                {isOpen && (
                  <div className="bg-slate-950/60 border border-slate-900/60 p-3 rounded-lg text-[10px] font-sans text-slate-400 max-w-xl">
                    <strong className="text-cyan-400 font-mono">Suggested Response: </strong>
                    {alert.recommendedAction}
                  </div>
                )}
              </div>

              {/* Action buttons */}
              <div className="flex flex-row md:flex-col justify-end gap-2 shrink-0 self-start md:self-center w-full md:w-auto border-t md:border-t-0 border-slate-900 pt-3 md:pt-0">
                <button 
                  onClick={() => handleInvestigate(alert)}
                  className="flex-1 md:flex-initial px-3 py-1.5 bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs rounded transition-all cursor-pointer text-center"
                >
                  Investigate
                </button>
                
                {isOpen && (
                  <div className="flex gap-2 w-full">
                    <button 
                      onClick={() => handleResolve(alert.id, 'resolved')}
                      className="flex-1 px-2.5 py-1.5 rounded border border-slate-800 hover:bg-slate-800 text-emerald-400 text-xs cursor-pointer transition-all flex items-center justify-center gap-0.5"
                    >
                      <Check size={12} />
                      Resolve
                    </button>
                    <button 
                      onClick={() => handleResolve(alert.id, 'dismissed')}
                      className="flex-1 px-2.5 py-1.5 rounded border border-slate-800 hover:bg-slate-800 text-slate-500 text-xs cursor-pointer transition-all flex items-center justify-center gap-0.5"
                    >
                      <X size={12} />
                      Dismiss
                    </button>
                  </div>
                )}
              </div>

            </div>
          );
        })}

        {filteredAlerts.length === 0 && (
          <div className="glass-panel p-12 rounded-2xl border border-slate-850 text-center text-slate-500 font-mono text-xs">
            No system notifications match the specified active filters.
          </div>
        )}
      </div>

    </div>
  );
};
export default AlertsCenter;
